server:
  port : 8881

spring:
  application:
    name: rating-service
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      database: reactive-microservices

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

