server:
  port : 8880

spring:
  application:
    name: book-service
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      database: reactive-microservices

#reactor:
#  netty:
#    ioWorkerCount: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG



